config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  resource :user, only: :show
  resources :requests, only: %i[new create] do
    get :attendee_requests, on: :collection
    get :owner_requests, on: :collection
    post :bulk_create, on: :collection
    patch :approve, on: :member
    patch :reject, on: :member
  end

  resources :events do
    member do
      delete :leave
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, presence: true

  belongs_to :creator, class_name: "User"
  has_many :requests, -> { where(requestor: "attendee") }, foreign_key: :event_id

  # We can directly use the default Rails functionality by not specifying the join_table and foreign_key.
  # Rails will automatically use the 'events_users' join table with 'event_id' and 'user_id' columns.
  # However, if we need to use a custom join table or different foreign keys, we can specify them as follows.
  has_and_belongs_to_many :attendees,
                          class_name: "User",
                          dependent: :destroy,
                          join_table: 'attended_events_attendees',
                          foreign_key: :attended_event_id,
                          association_foreign_key: :attendee_id

  enum :event_type, { public: 'public', private: 'private' }, prefix: true

  scope :past, -> { where('date < ? OR date = ? AND end_time < ?', Date.today, Date.today, Time.now) }
  scope :upcoming, -> { where('date > ? OR date = ? AND start_time > ?', Date.today, Date.today, Time.now) }
  scope :active, -> { where('date = ? AND start_time <= ? AND end_time >= ?', Date.today, Time.now, Time.now) }
  scope :others, ->(current_user){ where.not(creator: current_user) }

  accepts_nested_attributes_for :requests

  def destroy_with_associated_requests
    Request.where(event: self).destroy_all
    destroy
  end

  def start_at
    start_time.strftime('%H:%M')
  end

  def end_at
    end_time.strftime('%H:%M')
  end

  def past?
    date < Date.today || (date == Date.today && end_time < Time.now)
  end

  def upcoming?
    date > Date.today || (date == Date.today && start_time > Time.now)
  end

  def active?
    date == Date.today && start_time <= Time.now && end_time >= Time.now
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy join leave]

  def index
    @events = Event.others(current_user)
    @all_count = @events.count
    @past_count = @events.past.count
    @active_count = @events.active.count
    @upcoming_count = @events.upcoming.count
    @events = @events.send(params[:event_category]) if params[:event_category].present?
  end

  def show; end

  def new
    @event = current_user.events.build
  end

  def edit; end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('events.created_success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('events.updated_success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @event.destroy_with_associated_requests
      redirect_to user_path, notice: I18n.t('events.destroyed_success')
    else
      redirect_to fallback_location: @event, alert: I18n.t('events.destroy_failed')
    end
  end

  def leave
    if @event.attendees.delete(current_user)
      Request.where(attendee: current_user, event: @event).last&.update(status: 'leave')
      redirect_to fallback_location: @event, notice: I18n.t('events.leave_success')
    else
      redirect_to fallback_location: @event, alert: I18n.t('events.leave_failed')
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :location, :date, :start_time, :end_time, :event_type,
                                  requests_attributes: %i[id attendee_id requestor])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def render_button_based_on_requests(event, current_user)
    if current_user_requests(event).pending.exists?
      button_to "Request sent", "#", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded", disabled: true
    elsif event_requests(event).empty? || current_user_requests(event).where(status: ['leave', 'rejected']).exists?
      button_to "Join Request", requests_path(request: { event_id: event.id, requestor: 'attendee' }), method: :post, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
    end
  end

  def render_creator_buttons(event)
    buttons = []
    buttons << link_to("Add Attendee", new_request_path(event_id: event.id), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded")
    buttons << link_to("Edit", edit_event_path(event), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded")
    buttons << button_to("Delete", event, method: :delete, data: { confirm: "Are you sure?" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded")
    buttons.join.html_safe
  end

  def current_user_requests(event)
    event_requests(event).where(attendee_id: current_user.id)
  end

  def event_requests(event)
    event.requests
  end
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="bg-white shadow-md rounded-lg p-6 mb-4">
  <h2 class="text-2xl font-semibold mb-4">Event Details</h2>
  
  <div class="mb-4">
    <strong>Name:</strong>
    <span><%= event.name %></span>
  </div>

  <div class="mb-4">
    <strong>Location:</strong>
    <span><%= event.location %></span>
  </div>

  <div class="mb-4">
    <strong>Date:</strong>
    <span><%= event.date.strftime('%b %d, %Y') %></span>
  </div>

  <div class="mb-4">
    <strong>Start Time:</strong>
    <span><%= event.start_at %></span>
  </div>

  <div class="mb-4">
    <strong>End Time:</strong>
    <span><%= event.end_at %></span>
  </div>

  <div class="mb-4">
    <strong>Event Type</strong>
    <span><%= event.event_type %></span>
  </div>

  <div class="mb-4">
    <strong>Attendees:</strong>
    <% if event.attendees.any? %>
      <ul>
        <% event.attendees.each do |attendee| %>
          <li><%= attendee.email %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No attendees for this event.</p>
    <% end %>
  </div>
</div>

app/views/events/_events.html.erb
<% if events.any? %>
  <table class="w-full">
    <thead>
      <tr>
        <th class="text-left">Name</th>
        <th class="text-left">Date</th>
        <th class="text-left">Creator Email</th>
        <th class="text-left">Event Type</th>
        <th class="text-right">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% events.each do |event| %>
        <tr class="border-b">
          <td><%= event.name %></td>
          <td><%= event.date&.strftime('%b %d, %Y') %></td>
          <td><%= event.creator.email %></td>
          <td><%= event.event_type %></td>
          <td class="text-right">
            <div class="flex justify-end space-x-2">
              <% if event.upcoming? %>
                <% if event.attendees.include?(current_user) %>
                  <%= button_to "Leave", leave_event_path(event), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
                <% elsif event.creator != current_user %>
                  <%= render_button_based_on_requests(event, current_user) %>
                <% end %>
              <% end %>
  
              <%= link_to "View", event, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
              <% if current_user == event.creator %>
                <%= render_creator_buttons(event) %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No events found.</p>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "max-w-md mx-auto w-full") do |form| %>
  <% if event.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <h2 class="font-bold mb-2"><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :name, class: "form-input w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :location, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :location, class: "form-input w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :date, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.date_field :date, value: Date.today, class: "form-input w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :start_time, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.time_field :start_time, value: Time.now.strftime('%H:%M'), class: "form-input w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :end_time, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.time_field :end_time, value: (Time.now + 1.hour).strftime('%H:%M'), class: "form-input w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :event_type, "Event Type", class: "block text-gray-700 font-bold mb-2" %>

    <div class="flex items-center space-x-4">
      <label for="private_event" class="flex items-center cursor-pointer">
        <%= form.radio_button :event_type, "private", id: "private_event", class: "mr-2" %>
        <span class="text-gray-700 font-bold">Private</span>
      </label>

      <label for="public_event" class="flex items-center cursor-pointer">
        <%= form.radio_button :event_type, "public", id: "public_event", class: "mr-2" %>
        <span class="text-gray-700 font-bold">Public</span>
      </label>
    </div>
  </div>

  <div>
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="flex justify-between items-center mb-4">
  <a href="javascript:history.go(-1)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Back</a>
  <%#= link_to "Back", events_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %> 
  <%= link_to "Show Details", @event, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %> 
</div>

<h1 class="text-2xl font-semibold mb-4">Editing Event</h1>
<div class="max-w-md mx-auto">
  <%= render "form", event: @event %> 
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold">Events</h1>

    <%= link_to "New event", new_event_path, class: "bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded" %>
  </div>

  <div id="listing" class="bg-white shadow-md rounded-lg p-6 mb-4">
  <div class="border border-gray-300 rounded-lg">
    <div class="flex">
      <%= link_to root_path(), class: "tab-button w-full py-2 px-4 text-sm font-medium text-gray-600 bg-gray-100 bg-gray-200 rounded-t-lg hover:bg-gray-200 focus:outline-none focus:bg-gray-200" do %>
        All <span class="badge rounded-full bg-blue-500 text-white text-xs px-2"><%= @all_count %></span>
      <% end %>

      <%= link_to root_path(event_category: 'past'), class: "tab-button w-full py-2 px-4 text-sm font-medium text-gray-600 bg-gray-100 bg-gray-200 rounded-t-lg hover:bg-gray-200 focus:outline-none focus:bg-gray-200" do %>
        Past <span class="badge rounded-full bg-blue-500 text-white text-xs px-2"><%= @past_count %></span>
      <% end %>

      <%= link_to root_path(event_category: 'active'), class: "tab-button w-full py-2 px-4 text-sm font-medium text-gray-600 bg-gray-100 bg-gray-200 rounded-t-lg hover:bg-gray-200 focus:outline-none focus:bg-gray-200" do %>
        Active <span class="badge rounded-full bg-blue-500 text-white text-xs px-2"><%= @active_count %></span>
      <% end %>

      <%= link_to root_path(event_category: 'upcoming'), class: "tab-button w-full py-2 px-4 text-sm font-medium text-gray-600 bg-gray-100 bg-gray-200 rounded-t-lg hover:bg-gray-200 focus:outline-none focus:bg-gray-200" do %>
        Upcoming <span class="badge rounded-full bg-blue-500 text-white text-xs px-2"><%= @upcoming_count %></span>
      <% end %>
    </div>


    <div class="p-4">
        <%= render partial: "events/events", locals: { current_user: current_user, events: @events } %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="flex justify-start mb-4">
  <a href="javascript:history.go(-1)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Back</a>
</div>
<h1 class="text-2xl font-semibold mb-4">New Event</h1>
<div class="max-w-md mx-auto">
  <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex justify-between items-center mb-4">
  <a href="javascript:history.go(-1)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Back</a>

  <div class="ml-auto flex space-x-2">
    <% if @event.upcoming? %>
      <% if @event.attendees.include?(current_user) %>
        <%= button_to "Leave", leave_event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <% elsif @event.creator != current_user %>
        <%= render_button_based_on_requests(@event, current_user) %>
      <% end %>
    <% end %>
    <% if current_user == @event.creator %>
      <%= render_creator_buttons(@event) %>
    <% end %>
  </div>
</div>

<%= render partial: "events/event", locals: { event: @event } %>