config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  resource :user, only: :show
  resources :requests, only: %i[new create] do
    get :attendee_requests, on: :collection
    get :owner_requests, on: :collection
    post :bulk_create, on: :collection
    patch :approve, on: :member
    patch :reject, on: :member
  end

  resources :events do
    member do
      delete :leave
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, presence: true

  belongs_to :creator, class_name: "User"
  has_many :requests, -> { where(requestor: "attendee") }, foreign_key: :event_id

  # We can directly use the default Rails functionality by not specifying the join_table and foreign_key.
  # Rails will automatically use the 'events_users' join table with 'event_id' and 'user_id' columns.
  # However, if we need to use a custom join table or different foreign keys, we can specify them as follows.
  has_and_belongs_to_many :attendees,
                          class_name: "User",
                          dependent: :destroy,
                          join_table: 'attended_events_attendees',
                          foreign_key: :attended_event_id,
                          association_foreign_key: :attendee_id

  enum :event_type, { public: 'public', private: 'private' }, prefix: true

  scope :past, -> { where('date < ? OR date = ? AND end_time < ?', Date.today, Date.today, Time.now) }
  scope :upcoming, -> { where('date > ? OR date = ? AND start_time > ?', Date.today, Date.today, Time.now) }
  scope :active, -> { where('date = ? AND start_time <= ? AND end_time >= ?', Date.today, Time.now, Time.now) }
  scope :others, ->(current_user){ where.not(creator: current_user) }

  accepts_nested_attributes_for :requests

  def destroy_with_associated_requests
    Request.where(event: self).destroy_all
    destroy
  end

  def start_at
    start_time.strftime('%H:%M')
  end

  def end_at
    end_time.strftime('%H:%M')
  end

  def past?
    date < Date.today || (date == Date.today && end_time < Time.now)
  end

  def upcoming?
    date > Date.today || (date == Date.today && start_time > Time.now)
  end

  def active?
    date == Date.today && start_time <= Time.now && end_time >= Time.now
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"

  enum :status, { pending: 'pending', approved: 'approved', rejected: 'rejected', leave: 'leave'}
  enum :requestor, { owner: 'owner', attendee: 'attendee'}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, only: %i[approve reject]

  def new
    set_event(params[:event_id])
    @request = Request.new
    @users = User.select(:id, :email).where.not(id: @event.attendees.ids << current_user.id)
  end

  def bulk_create
    set_event(params[:request][:event_id])
    requests_data = params[:request][:attendee_ids].map { |attendee_id| { attendee_id: attendee_id, requestor: 'owner' } }

    if @event.requests.create(requests_data)
      redirect_to @event, notice: I18n.t('requests.bulk_create_success')
    else
      redirect_to @event, alert: I18n.t('requests.bulk_create_failure')
    end
  end

  def create
    @request = current_user.attendee_requests.build(request_params)

    if @request.save
      redirect_back fallback_location: root_path, notice: I18n.t('requests.create_success')
    else
      redirect_back fallback_location: root_path, alert: I18n.t('requests.create_failure')
    end
  end

  def approve
    @event = @request.event

    if @request.update(status: :approved)
      @event.attendees << @request.attendee
      redirect_back fallback_location: root_path, notice: I18n.t('requests.approve_success')
    else
      redirect_back fallback_location: root_path, alert: I18n.t('requests.approve_failure')
    end
  end

  def reject
    if @request.update(status: :rejected)
      redirect_back fallback_location: root_path, notice: I18n.t('requests.reject_success')
    else
      redirect_back fallback_location: root_path, alert: I18n.t('requests.reject_failure')
    end
  end

  def attendee_requests
    @requests = current_user.attendee_requests.pending
  end

  def owner_requests
    @requests = current_user.owner_requests.pending
  end

  def request_params
    params.require(:request).permit(:requestor, :event_id, :attendee_id)
  end

  def set_event(event_id)
    @event = Event.find(event_id)
  end

  def set_request
    @request = Request.find(params[:id])
  end
end

app/views/requests/_form.html.erb
<%= form_with(model: @request, url: bulk_create_requests_path, local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :name, 'Event:', class: "block text-gray-700 font-bold mb-2" %>
    <div class="flex items-center">
      <span class="inline-block bg-gray-200 text-gray-700 px-3 py-1 rounded-lg shadow-sm">
        <%= @event.name %>
      </span>
    </div>
    <%= form.hidden_field :event_id, value: @event.id %>
  </div>
  
  <div class="mb-4">
    <%= form.label :attendee_ids, 'Attendees:', class: "block text-gray-700 font-bold mb-2" %>
    <%= form.select :attendee_ids, options_for_select(@users.map { |user| [user.email, user.id] }, @users.first.id), { include_hidden: false }, { multiple: true, class: "form-multiselect w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-500 focus:border-blue-500" } %>
  </div>
 
  <%= form.submit "Create Requests", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/requests/_requests.html.erb
<% if requests.any? %>
  <table class="w-full">
    <thead>
      <tr>
        <th class="text-left">Event Name</th>
        <th class="text-left">Event Date</th>
        <th class="text-left">Requestor</th>
        <th class="text-right">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% requests.each do |request| %>
        <tr class="border-b">
          <td><%= request.event.name %></td>
          <td><%= request.event.date&.strftime('%b %d, %Y') %></td>
          <td><%= request.requestor == 'owner' ? request.event.creator.email : request.attendee.email %></td>
          <td class="text-right">
            <div class="flex justify-end space-x-2">
              <%= button_to "Approve", approve_request_path(request), method: :patch, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded", data: { confirm: "Are you sure you want to approve this request?" } %>
              <%= button_to "Reject", reject_request_path(request), method: :patch, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", data: { confirm: "Are you sure you want to reject this request?" } %>
              <%= link_to "View", request.event, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No requests found.</p>
<% end %>

app/views/requests/attendee_requests.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold">My Requests</h1>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6 mb-4">
    <%= render partial: "requests", locals: { requests: @requests } %>
  </div>
</div>

app/views/requests/new.html.erb
<div class="flex justify-start mb-4">
  <a href="javascript:history.go(-1)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Back</a>
</div>
<h1 class="text-2xl font-semibold mb-4">Invite Attendees</h1>
<div class="max-w-md mx-auto">
  <%= render "form", request: @request %>
</div>

app/views/requests/owner_requests.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold">Events Request</h1>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6 mb-4">
    <%= render partial: "requests", locals: { requests: @requests } %>
  </div>
</div>